---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ directories }}"
  ignore_errors: yes

- name: Deploy config
  copy:
    content: "{{ config_content }}"
    dest: "{{ config_path }}"
  ignore_errors: yes
