events {}
http {
server {
listen 443 ssl;
server_name demo.local;

ssl_certificate /etc/nginx/certs/demo.crt;
ssl_certificate_key /etc/nginx/certs/demo.key;

location /status {
return 200 "HTTPS OK";
add_header Content-Type text/plain;
}
}
}